name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build OpenedX
        run: docker build . --file ./Dockerfile --tag eoluchile/edx-tubular:${GITHUB_SHA} --tag eoluchile/edx-tubular:latest

      - name: Push
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          docker push eoluchile/edx-tubular:${GITHUB_SHA}
          docker push eoluchile/edx-tubular:latest
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

